var questions = 2;
var questionsLeft = ' [' + questions + ' questions left]';
var tale = "<h2> there was a time a ";
var noun = prompt("Hello there, give me a noun " + questionsLeft);
questions -= 1;
var questionsLeft = ' [' + questions + ' questions left]';
tale +=  noun;
console.log(noun);
console.log(tale);
var verb = prompt("Hello again, give me a verb please" + questionsLeft);
console.log(verb);
tale += " that really enjoys to " + verb + ".</h2>";
document.write(tale);
